//! Declarative, compile-time module registry.
//!
//! The [`ModuleDef`] struct is the single source of truth: every module
//! is one row in [`registry_defs`]. Conversion to the API-facing
//! [`ModuleInfo`] happens via [`materialize`] (compile-time only) and
//! [`module_registry_static`] (full static list without DB overrides).
//! Runtime overrides are applied in [`super::module_registry`].

use super::schemas::{
    MOD_ANNOUNCEMENTS_SCHEMA, MOD_EMAIL_TEMPLATES_SCHEMA, MOD_NOTIFICATIONS_SCHEMA,
    MOD_RECOMMENDATIONS_SCHEMA, MOD_THEMES_SCHEMA, MOD_WIDGETS_SCHEMA,
};
use super::{ConfigSchema, ModuleCategory, ModuleInfo};

/// Declarative, compile-time row in the module registry. `const`-friendly
/// so future introspection (e.g. generating docs from the table) stays
/// zero-allocation. Converted to a serializable [`ModuleInfo`] on demand.
#[derive(Debug, Clone, Copy)]
pub(super) struct ModuleDef {
    /// Stable slug — matches the feature flag without the `mod-` prefix.
    pub(super) name: &'static str,
    pub(super) category: ModuleCategory,
    pub(super) description: &'static str,
    /// Whether the binary was compiled with this module's feature flag.
    /// Evaluated at the call site with `cfg!(feature = "mod-...")`.
    pub(super) enabled: bool,
    /// Whether the module honours a runtime admin-setting override.
    ///
    /// `true` for modules that can be flipped off at runtime without a
    /// rebuild (low blast-radius, safe-to-toggle surfaces — UI widgets,
    /// display-only integrations, experimental features).
    ///
    /// `false` for modules whose runtime toggle would be a foot-gun
    /// (payments, RBAC, SSO, audit export, compliance, multi-tenant —
    /// anything that guards money, identity, or the audit trail). These
    /// can only be disabled by a rebuild, matching their security
    /// weight.
    pub(super) runtime_toggleable: bool,
    /// Admin-settings keys the module consumes. UI links each to the
    /// corresponding admin-settings section.
    pub(super) config_keys: &'static [&'static str],
    /// Deep-link into the user-facing UI (e.g. `/admin/plugins`). `None`
    /// means the module has no dedicated page and surfaces only via
    /// background behavior.
    pub(super) ui_route: Option<&'static str>,
    /// Other module slugs that must also be enabled for this to work.
    /// Validated at test time — broken references fail the test suite.
    pub(super) depends_on: &'static [&'static str],
    /// Optional JSON Schema (draft 2020-12) literal describing the
    /// module's admin config payload.
    ///
    /// When `Some(_)`, the module gains a pair of admin-only endpoints
    /// under `/api/v1/admin/modules/{name}/config`. `None` — the default
    /// for every module — means the module has no generic config editor
    /// and both endpoints return `400 BAD_REQUEST`.
    ///
    /// The literal must parse as a valid JSON object; [`module_registry_static`]
    /// validates the shape on startup / in tests (see
    /// `test_config_schema_strings_are_valid_json`).
    pub(super) config_schema: Option<&'static str>,
}

/// Convert a compile-time [`ModuleDef`] into an owned [`ModuleInfo`]
/// **without** applying any runtime setting overrides.
///
/// This is the pure compile-time view — used by tests, by callers that
/// don't need the admin-settings override, and as the starting point
/// for [`super::module_registry`] before it applies overrides.
///
/// A malformed `config_schema` string (non-JSON) is treated as "no
/// schema declared" for this row: we emit a `tracing::error!` and set
/// `config_schema = None` rather than panicking, so one typo doesn't
/// take the entire modules endpoint down. The
/// `test_config_schema_strings_are_valid_json` test guarantees we never
/// actually ship a broken literal.
pub(super) fn materialize(def: &ModuleDef) -> ModuleInfo {
    let config_schema =
        def.config_schema
            .and_then(|src| match serde_json::from_str::<serde_json::Value>(src) {
                Ok(schema) => Some(ConfigSchema { schema }),
                Err(e) => {
                    tracing::error!(
                        module = def.name,
                        error = %e,
                        "module config_schema literal is not valid JSON; dropping"
                    );
                    None
                }
            });

    ModuleInfo {
        name: def.name.to_string(),
        category: def.category,
        description: def.description.to_string(),
        enabled: def.enabled,
        runtime_toggleable: def.runtime_toggleable,
        runtime_enabled: def.enabled,
        config_keys: def.config_keys.iter().map(|s| (*s).to_string()).collect(),
        ui_route: def.ui_route.map(std::string::ToString::to_string),
        depends_on: def.depends_on.iter().map(|s| (*s).to_string()).collect(),
        version: env!("CARGO_PKG_VERSION").to_string(),
        config_schema,
    }
}

/// Pure compile-time view of the registry — no settings lookup, no DB
/// access. Useful for tests and for handlers that only need to check
/// `enabled` / metadata, not the effective runtime state.
#[must_use]
pub fn module_registry_static() -> Vec<ModuleInfo> {
    registry_defs().iter().map(materialize).collect()
}

/// The one and only declarative registry. Every module lives here;
/// new modules are added as a single row.
///
/// Kept as a private function (rather than a `const`) because `cfg!`
/// expands to a non-const boolean expression. The function is fully
/// stateless — the compiler optimizes each `cfg!` to a constant and
/// the whole vector collapses to a set of literal bool writes.
#[allow(clippy::too_many_lines)]
pub(super) fn registry_defs() -> Vec<ModuleDef> {
    vec![
        // ── Core ────────────────────────────────────────────────────────────
        ModuleDef {
            name: "bookings",
            category: ModuleCategory::Core,
            description: "Create, edit, cancel, and query reservations.",
            enabled: cfg!(feature = "mod-bookings"),
            runtime_toggleable: false,
            config_keys: &[
                "require_vehicle",
                "min_booking_duration_hours",
                "license_plate_mode",
            ],
            ui_route: Some("/bookings"),
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "vehicles",
            category: ModuleCategory::Core,
            description: "User-owned vehicle records with plates and default selection.",
            enabled: cfg!(feature = "mod-vehicles"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: Some("/vehicles"),
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "zones",
            category: ModuleCategory::Core,
            description: "Organizational groupings of slots (Level A/B, EV row, visitor row).",
            enabled: cfg!(feature = "mod-zones"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: Some("/admin/zones"),
            depends_on: &[],
            config_schema: None,
        },
        // ── Booking-side ────────────────────────────────────────────────────
        ModuleDef {
            name: "absences",
            category: ModuleCategory::Booking,
            description: "Home-office, vacation, sick, training — drives auto-release of booked slots.",
            enabled: cfg!(feature = "mod-absences"),
            runtime_toggleable: false,
            config_keys: &["auto_release_on_absence"],
            ui_route: Some("/absences"),
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "absence-approval",
            category: ModuleCategory::Booking,
            description: "Manager approval workflow for absence requests.",
            enabled: cfg!(feature = "mod-absence-approval"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &["absences"],
            config_schema: None,
        },
        ModuleDef {
            name: "recurring",
            category: ModuleCategory::Booking,
            description: "Weekly / monthly recurring bookings with rule engine.",
            enabled: cfg!(feature = "mod-recurring"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &["bookings"],
            config_schema: None,
        },
        ModuleDef {
            name: "guest",
            category: ModuleCategory::Booking,
            description: "Guest passes — share a time-limited booking with an external visitor.",
            enabled: cfg!(feature = "mod-guest"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &["bookings"],
            config_schema: None,
        },
        ModuleDef {
            name: "swap",
            category: ModuleCategory::Booking,
            description: "Peer-to-peer booking swaps between users.",
            enabled: cfg!(feature = "mod-swap"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &["bookings"],
            config_schema: None,
        },
        ModuleDef {
            name: "waitlist",
            category: ModuleCategory::Booking,
            description: "Waitlist notify-on-availability.",
            enabled: cfg!(feature = "mod-waitlist"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "waitlist-ext",
            category: ModuleCategory::Booking,
            description: "Advanced waitlist — priority, expiry, multi-slot.",
            enabled: cfg!(feature = "mod-waitlist-ext"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &["waitlist"],
            config_schema: None,
        },
        ModuleDef {
            name: "sharing",
            category: ModuleCategory::Booking,
            description: "Shareable booking links with QR + guest registration.",
            enabled: cfg!(feature = "mod-sharing"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &["bookings"],
            config_schema: None,
        },
        ModuleDef {
            name: "calendar",
            category: ModuleCategory::Booking,
            description: "Weekly/monthly calendar view of bookings.",
            enabled: cfg!(feature = "mod-calendar"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: Some("/calendar"),
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "calendar-drag",
            category: ModuleCategory::Booking,
            description: "Drag-and-drop reschedule in the calendar view.",
            enabled: cfg!(feature = "mod-calendar-drag"),
            runtime_toggleable: true,
            config_keys: &[],
            ui_route: None,
            depends_on: &["calendar"],
            config_schema: None,
        },
        ModuleDef {
            name: "favorites",
            category: ModuleCategory::Booking,
            description: "Pin a lot/slot as a favorite for one-tap booking.",
            enabled: cfg!(feature = "mod-favorites"),
            runtime_toggleable: true,
            config_keys: &[],
            ui_route: Some("/favorites"),
            depends_on: &[],
            config_schema: None,
        },
        // ── Vehicle / Fleet ─────────────────────────────────────────────────
        ModuleDef {
            name: "fleet",
            category: ModuleCategory::Vehicle,
            description: "Fleet admin — shared pool vehicles, utilization reports.",
            enabled: cfg!(feature = "mod-fleet"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: Some("/admin/fleet"),
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "qr",
            category: ModuleCategory::Vehicle,
            description: "QR codes for booking confirmations + slot check-in.",
            enabled: cfg!(feature = "mod-qr"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "parking-pass",
            category: ModuleCategory::Vehicle,
            description: "Printable / digital parking pass with QR barcode.",
            enabled: cfg!(feature = "mod-parking-pass"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: None,
        },
        // ── Payment ─────────────────────────────────────────────────────────
        ModuleDef {
            name: "payments",
            category: ModuleCategory::Payment,
            description: "Generic payment provider abstraction.",
            enabled: cfg!(feature = "mod-payments"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "stripe",
            category: ModuleCategory::Payment,
            description: "Stripe checkout + webhook integration.",
            enabled: cfg!(feature = "mod-stripe"),
            runtime_toggleable: false,
            config_keys: &["stripe_publishable_key"],
            ui_route: None,
            depends_on: &["payments"],
            config_schema: None,
        },
        ModuleDef {
            name: "credits",
            category: ModuleCategory::Payment,
            description: "Virtual credits balance — per-user monthly quota.",
            enabled: cfg!(feature = "mod-credits"),
            runtime_toggleable: false,
            config_keys: &["credits_enabled", "credits_per_booking"],
            ui_route: Some("/credits"),
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "invoices",
            category: ModuleCategory::Payment,
            description: "Per-booking PDF invoice generation.",
            enabled: cfg!(feature = "mod-invoices"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "dynamic-pricing",
            category: ModuleCategory::Payment,
            description: "Time-of-day and occupancy-based price curves.",
            enabled: cfg!(feature = "mod-dynamic-pricing"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: None,
        },
        // ── Admin ───────────────────────────────────────────────────────────
        ModuleDef {
            name: "rbac",
            category: ModuleCategory::Admin,
            description: "Role-based access control — admin, manager, user, guest.",
            enabled: cfg!(feature = "mod-rbac"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "sso",
            category: ModuleCategory::Admin,
            description: "OIDC-based single sign-on for external IdPs.",
            enabled: cfg!(feature = "mod-sso"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "audit-log",
            category: ModuleCategory::Admin,
            description: "Paginated admin audit trail with action, user, and date filters.",
            enabled: true,
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: Some("/admin/audit-log"),
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "audit-export",
            category: ModuleCategory::Admin,
            description: "Download the audit log as CSV/JSON.",
            enabled: cfg!(feature = "mod-audit-export"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: Some("/admin/audit"),
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "data-import",
            category: ModuleCategory::Admin,
            description: "Bulk import users/vehicles/lots from CSV.",
            enabled: cfg!(feature = "mod-data-import"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "import",
            category: ModuleCategory::Admin,
            description: "CSV and iCal import endpoints (bulk user / absence).",
            enabled: cfg!(feature = "mod-import"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "export",
            category: ModuleCategory::Admin,
            description: "GDPR and user-initiated data export.",
            enabled: cfg!(feature = "mod-export"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "settings",
            category: ModuleCategory::Admin,
            description: "Key-value runtime settings store for other modules.",
            enabled: cfg!(feature = "mod-settings"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: None,
        },
        // ── Analytics ───────────────────────────────────────────────────────
        ModuleDef {
            name: "admin-analytics",
            category: ModuleCategory::Analytics,
            description: "Admin dashboards — bookings, occupancy, revenue.",
            enabled: cfg!(feature = "mod-admin-analytics"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: Some("/admin/analytics"),
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "admin-reports",
            category: ModuleCategory::Analytics,
            description: "Admin booking, revenue, occupancy, and user growth reports.",
            enabled: true,
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: Some("/admin/reports"),
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "analytics",
            category: ModuleCategory::Analytics,
            description: "User-facing analytics — parking history trends.",
            enabled: cfg!(feature = "mod-analytics"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "scheduled-reports",
            category: ModuleCategory::Analytics,
            description: "Email cron for recurring admin reports.",
            enabled: cfg!(feature = "mod-scheduled-reports"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "metrics",
            category: ModuleCategory::Analytics,
            description: "Prometheus metrics exporter for scrape-based monitoring.",
            enabled: true,
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "rate-dashboard",
            category: ModuleCategory::Admin,
            description: "Admin rate-limit dashboard with live counters and 24-hour history.",
            enabled: true,
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: Some("/admin/rate-limits"),
            depends_on: &[],
            config_schema: None,
        },
        // ── Integration ─────────────────────────────────────────────────────
        ModuleDef {
            name: "webhooks",
            category: ModuleCategory::Integration,
            description: "Outbound webhooks (v1 — fire and forget).",
            enabled: cfg!(feature = "mod-webhooks"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "webhooks-v2",
            category: ModuleCategory::Integration,
            description: "Outbound webhooks with retry + signed payloads.",
            enabled: cfg!(feature = "mod-webhooks-v2"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "graphql",
            category: ModuleCategory::Integration,
            description: "GraphQL read/write API alongside REST.",
            enabled: cfg!(feature = "mod-graphql"),
            runtime_toggleable: true,
            config_keys: &[],
            ui_route: Some("/admin/graphql"),
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "api-docs",
            category: ModuleCategory::Integration,
            description: "Swagger UI + OpenAPI 3.1 spec export.",
            enabled: cfg!(feature = "mod-api-docs"),
            runtime_toggleable: true,
            config_keys: &[],
            ui_route: Some("/api/docs"),
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "api-versioning",
            category: ModuleCategory::Integration,
            description: "v1/v2 API surface with deprecation headers.",
            enabled: cfg!(feature = "mod-api-versioning"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "oauth",
            category: ModuleCategory::Integration,
            description: "OAuth2 callback handling (Google, GitHub, Microsoft).",
            enabled: cfg!(feature = "mod-oauth"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "ical",
            category: ModuleCategory::Integration,
            description: "Read-only iCal feed of bookings for calendar clients.",
            enabled: cfg!(feature = "mod-ical"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "realtime",
            category: ModuleCategory::Integration,
            description: "Real-time occupancy + booking events over the primary WebSocket transport.",
            enabled: cfg!(feature = "mod-websocket"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: None,
        },
        // ── Notification ────────────────────────────────────────────────────
        ModuleDef {
            name: "notifications",
            category: ModuleCategory::Notification,
            description: "In-app notification bell with per-event preferences.",
            enabled: cfg!(feature = "mod-notifications"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: Some("/notifications"),
            depends_on: &[],
            config_schema: Some(MOD_NOTIFICATIONS_SCHEMA),
        },
        ModuleDef {
            name: "notification-center",
            category: ModuleCategory::Notification,
            description: "Grouped notification feed with mark-read.",
            enabled: cfg!(feature = "mod-notification-center"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &["notifications"],
            config_schema: None,
        },
        ModuleDef {
            name: "announcements",
            category: ModuleCategory::Notification,
            description: "Admin-published banner announcements.",
            enabled: cfg!(feature = "mod-announcements"),
            runtime_toggleable: true,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: Some(MOD_ANNOUNCEMENTS_SCHEMA),
        },
        ModuleDef {
            name: "email",
            category: ModuleCategory::Notification,
            description: "SMTP delivery of transactional emails.",
            enabled: cfg!(feature = "mod-email"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "email-templates",
            category: ModuleCategory::Notification,
            description: "Handlebars templates editable from the admin UI.",
            enabled: cfg!(feature = "mod-email-templates"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &["email"],
            config_schema: Some(MOD_EMAIL_TEMPLATES_SCHEMA),
        },
        ModuleDef {
            name: "push",
            category: ModuleCategory::Notification,
            description: "Web Push subscription + VAPID delivery.",
            enabled: cfg!(feature = "mod-push"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: None,
        },
        // ── Compliance ──────────────────────────────────────────────────────
        ModuleDef {
            name: "compliance",
            category: ModuleCategory::Compliance,
            description: "Compliance tooling — export, evidence, attestations.",
            enabled: cfg!(feature = "mod-compliance"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "accessible",
            category: ModuleCategory::Compliance,
            description: "Accessible-slots policy + user accessibility needs.",
            enabled: cfg!(feature = "mod-accessible"),
            runtime_toggleable: true,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "gdpr",
            category: ModuleCategory::Compliance,
            description: "GDPR consent ledger, data-subject requests, right-to-be-forgotten.",
            enabled: true,
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "retention",
            category: ModuleCategory::Compliance,
            description: "GDPR retention / deletion policy engine: per-class TTLs, scheduled purge, deletion-evidence log.",
            enabled: true,
            runtime_toggleable: false,
            config_keys: &[
                "retention_policy_operational_presence",
                "retention_policy_booking_history",
                "retention_policy_security_audit_log",
                "retention_policy_hr_labour",
                "retention_policy_anpr_raw",
                "retention_policy_ev_session",
                "retention_policy_billing_fiscal",
            ],
            ui_route: Some("/admin/retention"),
            depends_on: &["gdpr"],
            config_schema: None,
        },
        // ── Enterprise ──────────────────────────────────────────────────────
        ModuleDef {
            name: "multi-tenant",
            category: ModuleCategory::Enterprise,
            description: "Multi-tenant isolation — per-tenant users, lots, branding.",
            enabled: cfg!(feature = "mod-multi-tenant"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "cost-center",
            category: ModuleCategory::Enterprise,
            description: "Per-cost-center reporting + allocation.",
            enabled: cfg!(feature = "mod-cost-center"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "themes",
            category: ModuleCategory::Enterprise,
            description: "Per-tenant theme / branding customization.",
            enabled: cfg!(feature = "mod-themes"),
            runtime_toggleable: true,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: Some(MOD_THEMES_SCHEMA),
        },
        ModuleDef {
            name: "plugins",
            category: ModuleCategory::Enterprise,
            description: "Runtime plugin loader for customer-side extensions.",
            enabled: cfg!(feature = "mod-plugins"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: Some("/admin/plugins"),
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "branding",
            category: ModuleCategory::Enterprise,
            description: "App name + logo customization.",
            enabled: cfg!(feature = "mod-branding"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "translations",
            category: ModuleCategory::Enterprise,
            description: "Per-tenant string overrides for i18n keys.",
            enabled: cfg!(feature = "mod-translations"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "parking-zones",
            category: ModuleCategory::Enterprise,
            description: "Advanced zone management + rules.",
            enabled: cfg!(feature = "mod-parking-zones"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "widgets",
            category: ModuleCategory::Enterprise,
            description: "Embeddable widgets for external dashboards.",
            enabled: cfg!(feature = "mod-widgets"),
            runtime_toggleable: true,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: Some(MOD_WIDGETS_SCHEMA),
        },
        // ── Experimental / Hardware ─────────────────────────────────────────
        ModuleDef {
            name: "ev-charging",
            category: ModuleCategory::Experimental,
            description: "EV-charging slots + charging-session metadata.",
            enabled: cfg!(feature = "mod-ev-charging"),
            runtime_toggleable: true,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "map",
            category: ModuleCategory::Experimental,
            description: "Map view of lots with live occupancy overlay.",
            enabled: cfg!(feature = "mod-map"),
            runtime_toggleable: true,
            config_keys: &[],
            ui_route: Some("/map"),
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "geofence",
            category: ModuleCategory::Experimental,
            description: "GPS-geofenced auto check-in.",
            enabled: cfg!(feature = "mod-geofence"),
            runtime_toggleable: true,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "visitors",
            category: ModuleCategory::Experimental,
            description: "Visitor badge + pre-registration.",
            enabled: cfg!(feature = "mod-visitors"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "maintenance",
            category: ModuleCategory::Experimental,
            description: "Slot maintenance windows + technician scheduling.",
            enabled: cfg!(feature = "mod-maintenance"),
            runtime_toggleable: true,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "history",
            category: ModuleCategory::Experimental,
            description: "Extended parking history view for users.",
            enabled: cfg!(feature = "mod-history"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: Some("/history"),
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "social",
            category: ModuleCategory::Experimental,
            description: "Leaderboards + social sharing.",
            enabled: cfg!(feature = "mod-social"),
            runtime_toggleable: true,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "recommendations",
            category: ModuleCategory::Experimental,
            description: "Configurable weighted slot recommendation engine.",
            enabled: cfg!(feature = "mod-recommendations"),
            runtime_toggleable: false,
            config_keys: &[
                "algorithm",
                "pipeline_endpoint",
                "pipeline_name",
                "pipeline_timeout_ms",
                "pipeline_fallback_enabled",
                "weight_frequency",
                "weight_preferred_lot",
                "weight_availability",
                "weight_price",
                "weight_distance",
                "weight_accessibility_bonus",
                "weight_feature_bonus",
                "max_results",
                "explain",
                "profile_safe_mode",
                "allocation_transparency_mode",
            ],
            ui_route: None,
            depends_on: &[],
            config_schema: Some(MOD_RECOMMENDATIONS_SCHEMA),
        },
        ModuleDef {
            name: "operating-hours",
            category: ModuleCategory::Experimental,
            description: "Lot operating-hours enforcement.",
            enabled: cfg!(feature = "mod-operating-hours"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "lobby-display",
            category: ModuleCategory::Experimental,
            description: "Kiosk / lobby-display mode for public screens.",
            enabled: cfg!(feature = "mod-lobby-display"),
            runtime_toggleable: true,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "team",
            category: ModuleCategory::Experimental,
            description: "Team-level booking + fair-share policies.",
            enabled: cfg!(feature = "mod-team"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "setup-wizard",
            category: ModuleCategory::Experimental,
            description: "First-run setup wizard for admins.",
            enabled: cfg!(feature = "mod-setup-wizard"),
            runtime_toggleable: true,
            config_keys: &[],
            ui_route: Some("/setup"),
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "jobs",
            category: ModuleCategory::Experimental,
            description: "Background job scheduling (cron, intervals).",
            enabled: cfg!(feature = "mod-jobs"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "pwa",
            category: ModuleCategory::Experimental,
            description: "Progressive Web App manifest + basic offline shell.",
            enabled: cfg!(feature = "mod-pwa"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: None,
        },
        ModuleDef {
            name: "enhanced-pwa",
            category: ModuleCategory::Experimental,
            description: "Enhanced PWA with booking prefetch and offline data.",
            enabled: cfg!(feature = "mod-enhanced-pwa"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &["pwa"],
            config_schema: None,
        },
        ModuleDef {
            name: "mobile",
            category: ModuleCategory::Experimental,
            description: "Mobile-specific surfaces (install prompt, haptics).",
            enabled: cfg!(feature = "mod-mobile"),
            runtime_toggleable: false,
            config_keys: &[],
            ui_route: None,
            depends_on: &[],
            config_schema: None,
        },
    ]
}
