//! TypeScript type export orchestrator (T-1941).
//!
//! This test runs only under the `gen-types` feature. It acts as the
//! authoritative "emit bindings to disk" entry point: it walks every DTO
//! that derives `#[ts_rs::TS]` across the workspace and calls
//! `T::export_all_to(...)` so each type writes its `.ts` file — plus every
//! transitively referenced type — into `parkhub-web/src/generated/types/`.
//! Relying on the explicit call rather than ts-rs' hidden
//! `export_bindings_<type>` auto-tests is intentional: running a single
//! `cargo test --features gen-types -p parkhub-server --test ts_export`
//! command emits the full graph, instead of requiring every crate's test
//! harness to run.
//!
//! After export, every `.ts` file gets a standard warning header prepended
//! so reviewers know not to hand-edit the generated output.
//!
//! # Run locally
//!
//! ```bash
//! cargo test --features gen-types -p parkhub-server --test ts_export -- --nocapture
//! ```
//!
//! After running, `git diff parkhub-web/src/generated/` shows whether the
//! Rust source drifted from the committed TypeScript bindings. The CI job
//! `types-drift` in `.github/workflows/ci.yml` runs the same command and
//! fails when the diff is non-empty.
//!
//! Licensing note: `ts-rs` is MIT OR Apache-2.0 and is compile-time /
//! dev-only — it never ships in release binaries.

#![cfg(feature = "gen-types")]

use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

use parkhub_common::models::{
    Absence, AbsencePattern, AbsenceType, Announcement, AnnouncementSeverity, AuthTokens, Booking,
    BookingPricing, BookingStatus, ChargingSession, ChargingSessionStatus, ConnectorType,
    CreditTransaction, CreditTransactionType, DayHours, DynamicPriceResult, DynamicPricingRules,
    EvCharger, EvChargerStatus, FleetEvent, FleetEventType, FuelType, GuestBooking, LotStatus,
    Notification, NotificationType, OperatingHours, ParkingFloor, ParkingLot, ParkingSlot,
    PaymentStatus, PricingInfo, PricingRate, ProposalStatus, SlotBookingInfo, SlotFeature,
    SlotPosition, SlotStatus, SlotType, SwapRequest, SwapRequestStatus, TranslationOverride,
    TranslationProposal, User, UserPreferences, UserRole, Vehicle, VehicleType,
};
use parkhub_common::protocol::{
    ApiError, ApiResponse, LoginRequest, LoginResponse, PaginatedResponse, RefreshTokenRequest,
    RegisterRequest, ResponseMeta,
};
use ts_rs::TS;

/// Header stamped on every generated `.ts` file so humans and linters know
/// the file is auto-generated. Kept ASCII and dependency-free.
const WARNING_HEADER: &str = "\
// Auto-generated by ts-rs. DO NOT EDIT.
// Regenerate with:
//   cargo test --features gen-types -p parkhub-server --test ts_export -- --nocapture
// Source of truth: parkhub-common/src/models.rs + protocol.rs
// (plus parkhub-server/src/api/{calendar,team}.rs for server-side DTOs).

";

/// Output directory for generated TypeScript types, relative to the
/// workspace root. This is the single source of truth for the output
/// path — the `#[ts(export)]` attributes on each type intentionally
/// carry no `export_to = "..."` so they inherit the directory passed
/// to `export_all_to` in the test below.
const OUTPUT_SUBDIR: &str = "parkhub-web/src/generated/types";

/// Minimum number of `.ts` files we expect in the output dir. If ts-rs
/// silently stops emitting (e.g. because a feature regression disables
/// derives) this guard catches it instead of letting the CI drift-gate
/// pass on an empty directory.
const MIN_EXPECTED_FILES: usize = 30;

fn workspace_root() -> PathBuf {
    // `CARGO_MANIFEST_DIR` for this test crate is parkhub-server/, so the
    // workspace root is its parent directory.
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest_dir
        .parent()
        .expect("parkhub-server has a parent (workspace root)")
        .to_path_buf()
}

fn output_dir() -> PathBuf {
    workspace_root().join(OUTPUT_SUBDIR)
}

fn prepend_header(path: &Path) -> std::io::Result<()> {
    let current = fs::read_to_string(path)?;
    if current.starts_with("// Auto-generated by ts-rs") {
        // Already stamped — keep run idempotent so CI diff only shows real
        // changes from Rust source.
        return Ok(());
    }
    let mut f = fs::File::create(path)?;
    f.write_all(WARNING_HEADER.as_bytes())?;
    f.write_all(current.as_bytes())?;
    Ok(())
}

/// Walk `dir` recursively and prepend the warning header to every `.ts`
/// file found. Counts stamped files (fresh + already-stamped skipped).
fn stamp_recursively(dir: &Path, stamped: &mut usize) -> std::io::Result<()> {
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_dir() {
            stamp_recursively(&path, stamped)?;
        } else if path.extension().and_then(|s| s.to_str()) == Some("ts") {
            prepend_header(&path)?;
            *stamped += 1;
        }
    }
    Ok(())
}

/// Export `T` and every type it transitively references.
///
/// Uses `export_all_to(dir)` with the absolute workspace-root-relative
/// output dir. The `#[ts(export)]` attributes on each type intentionally
/// DO NOT carry an `export_to = "..."` so the `dir` we pass here is
/// the single source of truth for the output path. This avoids ts-rs's
/// tendency to resolve relative `export_to` paths against the runtime
/// `CARGO_MANIFEST_DIR` of the test binary (parkhub-server) instead of
/// the derive's crate (parkhub-common), which otherwise writes bindings
/// into `parkhub-server/parkhub-web/...` — wrong tree.
fn export<T: TS + 'static>(dir: &Path) -> std::io::Result<()> {
    <T as TS>::export_all_to(dir).map_err(|e| std::io::Error::other(format!("ts-rs export: {e}")))
}

/// Purge any previously-emitted `.ts` files from `dir` before the next
/// export run. This is the deletion-drift half of the ts-rs gate: when a
/// Rust type is renamed or removed, ts-rs never writes a "tombstone" — it
/// just stops emitting the old file. Without this cleanup, the orphan
/// `.ts` lingers on disk and the CI diff check reports "no drift" even
/// though the generated tree is stale.
///
/// We keep the directory itself (so `export_all_to` doesn't recreate it
/// with the wrong permissions) and remove only `.ts` files plus any
/// subdirectories ts-rs may have created (e.g. `serde_json/`). Non-`.ts`
/// files are preserved so we don't accidentally nuke unrelated tooling
/// artefacts somebody might stash here.
fn clean_ts_output(dir: &Path) -> std::io::Result<()> {
    if !dir.exists() {
        return Ok(());
    }
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_dir() {
            fs::remove_dir_all(&path)?;
        } else if path.extension().and_then(|s| s.to_str()) == Some("ts") {
            fs::remove_file(&path)?;
        }
    }
    Ok(())
}

/// Remove the stray `bindings/` directories that ts-rs writes next to each
/// crate regardless of the path passed to `export_all_to`. Upstream ts-rs
/// emits external-crate helpers (e.g. `serde_json/JsonValue.ts`, chrono,
/// uuid glue) into `<crate_manifest_dir>/bindings/` in addition to the
/// directory we actually ask for — so `parkhub-server/bindings/` and
/// `parkhub-common/bindings/` get repopulated every run. They are already
/// gitignored, but we purge them here so local disks don't slowly
/// accumulate stale external-type copies and `git status` stays tidy.
///
/// The function is idempotent: missing directories are a no-op, existing
/// ones get removed. Called BEFORE the next export so the very next run
/// starts from a clean slate.
fn clean_stray_crate_bindings(workspace_root: &Path) -> std::io::Result<()> {
    for crate_name in ["parkhub-server", "parkhub-common"] {
        let stray = workspace_root.join(crate_name).join("bindings");
        if stray.exists() {
            fs::remove_dir_all(&stray)?;
        }
    }
    Ok(())
}

#[test]
fn clean_stray_crate_bindings_is_idempotent_and_removes_dirs() {
    // Regression guard for the ts-rs "external-crate helpers land in
    // `<crate>/bindings/` regardless of export_all_to()" quirk. The
    // cleanup must: (a) no-op when the dirs don't exist, (b) remove the
    // dirs and their contents when they do, (c) never touch anything
    // outside `bindings/`.
    let scratch = std::env::temp_dir().join(format!(
        "ts_export_stray_bindings_test_{}",
        std::process::id()
    ));
    let _ = fs::remove_dir_all(&scratch);
    fs::create_dir_all(&scratch).unwrap();

    // (a) idempotent no-op: no `bindings/` dirs present.
    clean_stray_crate_bindings(&scratch).expect("no-op when dirs missing");

    // (b) both crate bindings dirs get removed when present.
    let server_bindings = scratch.join("parkhub-server").join("bindings");
    let common_bindings = scratch.join("parkhub-common").join("bindings");
    fs::create_dir_all(&server_bindings).unwrap();
    fs::create_dir_all(&common_bindings).unwrap();
    fs::write(server_bindings.join("JsonValue.ts"), "// stray").unwrap();
    fs::write(common_bindings.join("Uuid.ts"), "// stray").unwrap();

    // (c) an unrelated sibling file must survive.
    let keep = scratch.join("parkhub-server").join("src.rs");
    fs::create_dir_all(keep.parent().unwrap()).unwrap();
    fs::write(&keep, "// unrelated").unwrap();

    clean_stray_crate_bindings(&scratch).expect("removes stray bindings dirs");

    assert!(
        !server_bindings.exists(),
        "parkhub-server/bindings/ must be removed"
    );
    assert!(
        !common_bindings.exists(),
        "parkhub-common/bindings/ must be removed"
    );
    assert!(keep.exists(), "unrelated sibling file must be preserved");

    // (d) calling again after removal is still a no-op.
    clean_stray_crate_bindings(&scratch).expect("idempotent after removal");

    let _ = fs::remove_dir_all(&scratch);
}

#[test]
fn clean_ts_output_removes_stale_files_but_keeps_dir() {
    // Regression for Codex #377 P2: when a Rust type is removed or renamed,
    // ts-rs stops emitting the old `.ts` file but never deletes it. The
    // drift check on git-tracked content still passes because the stale
    // file is unchanged. clean_ts_output must purge those orphans so the
    // next export produces a tree that reflects only the current Rust DTOs.
    let scratch = std::env::temp_dir().join(format!("ts_export_clean_test_{}", std::process::id()));
    let _ = fs::remove_dir_all(&scratch);
    fs::create_dir_all(&scratch).unwrap();

    let stale_type = scratch.join("RemovedType.ts");
    fs::write(&stale_type, "// orphan from a deleted Rust type").unwrap();
    let nested = scratch.join("serde_json");
    fs::create_dir_all(&nested).unwrap();
    fs::write(nested.join("JsonValue.ts"), "// orphan nested").unwrap();
    let keep = scratch.join("README.md");
    fs::write(&keep, "keep me — unrelated tooling file").unwrap();

    clean_ts_output(&scratch).expect("clean_ts_output succeeds");

    assert!(scratch.exists(), "directory itself must survive cleanup");
    assert!(!stale_type.exists(), "stale .ts file must be removed");
    assert!(!nested.exists(), "stale subdirectory must be removed");
    assert!(keep.exists(), "non-.ts file must be preserved");

    let _ = fs::remove_dir_all(&scratch);
}

#[test]
fn export_all_types() {
    let dir = output_dir();
    fs::create_dir_all(&dir).expect("create output dir");
    // Deletion-drift guard: purge last run's output so removed/renamed Rust
    // types surface as a diff (`git status --porcelain` will show a
    // disappeared file) instead of lingering forever as a stale orphan.
    clean_ts_output(&dir).expect("clean previous ts output");
    // Pre-run stray-bindings cleanup so the ts-rs quirk of writing
    // external-crate helpers into `<crate>/bindings/` doesn't leave stale
    // copies on disk across iterations (the dirs are gitignored, but we
    // don't want them accumulating locally).
    clean_stray_crate_bindings(&workspace_root()).expect("clean stray crate bindings (pre-run)");
    println!("ts_export: writing to {}", dir.display());

    // ── Protocol wrappers ────────────────────────────────────────────────
    // `ApiResponse<T>` and `PaginatedResponse<T>` are generic; ts-rs emits
    // a generic interface so a single export covers every T instantiation.
    export::<ApiResponse<()>>(&dir).unwrap();
    export::<ApiError>(&dir).unwrap();
    export::<ResponseMeta>(&dir).unwrap();
    export::<PaginatedResponse<()>>(&dir).unwrap();
    export::<LoginRequest>(&dir).unwrap();
    export::<LoginResponse>(&dir).unwrap();
    export::<RefreshTokenRequest>(&dir).unwrap();
    export::<RegisterRequest>(&dir).unwrap();

    // ── User ─────────────────────────────────────────────────────────────
    export::<User>(&dir).unwrap();
    export::<UserRole>(&dir).unwrap();
    export::<UserPreferences>(&dir).unwrap();
    export::<AuthTokens>(&dir).unwrap();

    // ── Parking lot / slot ──────────────────────────────────────────────
    export::<ParkingLot>(&dir).unwrap();
    export::<ParkingFloor>(&dir).unwrap();
    export::<ParkingSlot>(&dir).unwrap();
    export::<SlotType>(&dir).unwrap();
    export::<SlotStatus>(&dir).unwrap();
    export::<SlotBookingInfo>(&dir).unwrap();
    export::<SlotFeature>(&dir).unwrap();
    export::<SlotPosition>(&dir).unwrap();
    export::<LotStatus>(&dir).unwrap();
    export::<PricingInfo>(&dir).unwrap();
    export::<PricingRate>(&dir).unwrap();
    export::<OperatingHours>(&dir).unwrap();
    export::<DayHours>(&dir).unwrap();
    export::<DynamicPricingRules>(&dir).unwrap();
    export::<DynamicPriceResult>(&dir).unwrap();

    // ── Bookings + vehicles ─────────────────────────────────────────────
    export::<Booking>(&dir).unwrap();
    export::<BookingStatus>(&dir).unwrap();
    export::<BookingPricing>(&dir).unwrap();
    export::<PaymentStatus>(&dir).unwrap();
    export::<Vehicle>(&dir).unwrap();
    export::<VehicleType>(&dir).unwrap();
    export::<FuelType>(&dir).unwrap();
    export::<CreditTransaction>(&dir).unwrap();
    export::<CreditTransactionType>(&dir).unwrap();

    // ── Feature models used by v5 screens ───────────────────────────────
    export::<GuestBooking>(&dir).unwrap();
    export::<SwapRequest>(&dir).unwrap();
    export::<SwapRequestStatus>(&dir).unwrap();
    export::<Announcement>(&dir).unwrap();
    export::<AnnouncementSeverity>(&dir).unwrap();
    export::<Notification>(&dir).unwrap();
    export::<NotificationType>(&dir).unwrap();
    export::<AbsenceType>(&dir).unwrap();
    export::<Absence>(&dir).unwrap();
    export::<AbsencePattern>(&dir).unwrap();
    export::<ProposalStatus>(&dir).unwrap();
    export::<TranslationProposal>(&dir).unwrap();
    export::<TranslationOverride>(&dir).unwrap();

    // ── EV charging ─────────────────────────────────────────────────────
    export::<ConnectorType>(&dir).unwrap();
    export::<EvChargerStatus>(&dir).unwrap();
    export::<EvCharger>(&dir).unwrap();
    export::<ChargingSessionStatus>(&dir).unwrap();
    export::<ChargingSession>(&dir).unwrap();

    // ── Fleet SSE events (T-1946) ───────────────────────────────────────
    // Follow-up from #378: derive landed after #377 (ts-rs gen), so the
    // wire contract for `/api/v1/events/fleet` needs its TS bindings too.
    export::<FleetEvent>(&dir).unwrap();
    export::<FleetEventType>(&dir).unwrap();

    // Note: server-side DTOs in parkhub-server/src/api/{calendar,team}.rs
    // (CalendarEvent, TeamMember, TeamMemberStatus) also derive `TS` and
    // emit via the hidden `export_bindings_<type>` test that ts-rs adds
    // when the enclosing module is compiled as a test crate. Running
    // `cargo test --features gen-types -p parkhub-server` — which this
    // test file is part of — compiles the parkhub-server test binary and
    // triggers those hidden tests alongside `export_all_types`. The CI
    // workflow invokes exactly this command, so all three paths converge
    // on the same output directory.

    // ── Stamp warning header on every emitted .ts file ──────────────────
    // Walk recursively so files ts-rs emits into subdirectories (e.g.
    // `serde_json/JsonValue.ts` when `serde-json-impl` is enabled) also
    // pick up the header. Shallow readdir missed the subdir in earlier
    // iterations of this test.
    let mut stamped = 0usize;
    stamp_recursively(&dir, &mut stamped).expect("stamp headers recursively");
    assert!(
        stamped >= MIN_EXPECTED_FILES,
        "expected >= {MIN_EXPECTED_FILES} .ts files in {}, got {stamped}. \
         Either a feature regression turned off the ts-rs derives, or the \
         hidden export_bindings_* tests have not run yet.",
        dir.display(),
    );
    println!("ts_export: stamped warning header on {stamped} files");

    // ── Per-type presence guards ────────────────────────────────────────
    // `stamped >= MIN_EXPECTED_FILES` only catches wholesale regressions.
    // Specific follow-up types (FleetEvent/FleetEventType from #378) get
    // their own existence guards so a missing derive surfaces as a clear
    // failure instead of a silent drop inside the 30-file floor.
    for expected in ["FleetEvent.ts", "FleetEventType.ts"] {
        let p = dir.join(expected);
        assert!(
            p.exists(),
            "expected {} to be emitted by ts-rs; missing at {}",
            expected,
            p.display(),
        );
    }

    // ── Post-run stray-bindings cleanup ─────────────────────────────────
    // ts-rs writes a second copy of external-crate types (serde_json,
    // chrono, uuid glue) into `<crate>/bindings/` during export_all_to,
    // regardless of the destination path. Purge them so they don't
    // accumulate on disk between runs. Already gitignored; this keeps
    // `git status` tidy for developers running the test locally.
    clean_stray_crate_bindings(&workspace_root()).expect("clean stray crate bindings (post-run)");
}
