//! TypeScript type export orchestrator (T-1941).
//!
//! This test runs only under the `gen-types` feature. It acts as the
//! authoritative "emit bindings to disk" entry point: it walks every DTO
//! that derives `#[ts_rs::TS]` across the workspace and calls
//! `T::export_all_to(...)` so each type writes its `.ts` file — plus every
//! transitively referenced type — into `parkhub-web/src/generated/types/`.
//! Relying on the explicit call rather than ts-rs' hidden
//! `export_bindings_<type>` auto-tests is intentional: running a single
//! `cargo test --features gen-types -p parkhub-server --test ts_export`
//! command emits the full graph, instead of requiring every crate's test
//! harness to run.
//!
//! After export, every `.ts` file gets a standard warning header prepended
//! so reviewers know not to hand-edit the generated output.
//!
//! # Run locally
//!
//! ```bash
//! cargo test --features gen-types -p parkhub-server --test ts_export -- --nocapture
//! ```
//!
//! After running, `git diff parkhub-web/src/generated/` shows whether the
//! Rust source drifted from the committed TypeScript bindings. The CI job
//! `types-drift` in `.github/workflows/ci.yml` runs the same command and
//! fails when the diff is non-empty.
//!
//! Licensing note: `ts-rs` is MIT OR Apache-2.0 and is compile-time /
//! dev-only — it never ships in release binaries.

#![cfg(feature = "gen-types")]

use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

use parkhub_common::models::{
    Absence, AbsencePattern, AbsenceType, Announcement, AnnouncementSeverity, AuthTokens, Booking,
    BookingPricing, BookingStatus, ChargingSession, ChargingSessionStatus, ConnectorType,
    CreditTransaction, CreditTransactionType, DayHours, DynamicPriceResult, DynamicPricingRules,
    EvCharger, EvChargerStatus, FuelType, GuestBooking, LotStatus, Notification, NotificationType,
    OperatingHours, ParkingFloor, ParkingLot, ParkingSlot, PaymentStatus, PricingInfo, PricingRate,
    ProposalStatus, SlotBookingInfo, SlotFeature, SlotPosition, SlotStatus, SlotType, SwapRequest,
    SwapRequestStatus, TranslationOverride, TranslationProposal, User, UserPreferences, UserRole,
    Vehicle, VehicleType,
};
use parkhub_common::protocol::{
    ApiError, ApiResponse, LoginRequest, LoginResponse, PaginatedResponse, RefreshTokenRequest,
    RegisterRequest, ResponseMeta,
};
use ts_rs::TS;

/// Header stamped on every generated `.ts` file so humans and linters know
/// the file is auto-generated. Kept ASCII and dependency-free.
const WARNING_HEADER: &str = "\
// Auto-generated by ts-rs. DO NOT EDIT.
// Regenerate with:
//   cargo test --features gen-types -p parkhub-server --test ts_export -- --nocapture
// Source of truth: parkhub-common/src/models.rs + protocol.rs
// (plus parkhub-server/src/api/{calendar,team}.rs for server-side DTOs).

";

/// Output directory for generated TypeScript types, relative to the
/// workspace root. This is the single source of truth for the output
/// path — the `#[ts(export)]` attributes on each type intentionally
/// carry no `export_to = "..."` so they inherit the directory passed
/// to `export_all_to` in the test below.
const OUTPUT_SUBDIR: &str = "parkhub-web/src/generated/types";

/// Minimum number of `.ts` files we expect in the output dir. If ts-rs
/// silently stops emitting (e.g. because a feature regression disables
/// derives) this guard catches it instead of letting the CI drift-gate
/// pass on an empty directory.
const MIN_EXPECTED_FILES: usize = 30;

fn workspace_root() -> PathBuf {
    // `CARGO_MANIFEST_DIR` for this test crate is parkhub-server/, so the
    // workspace root is its parent directory.
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest_dir
        .parent()
        .expect("parkhub-server has a parent (workspace root)")
        .to_path_buf()
}

fn output_dir() -> PathBuf {
    workspace_root().join(OUTPUT_SUBDIR)
}

fn prepend_header(path: &Path) -> std::io::Result<()> {
    let current = fs::read_to_string(path)?;
    if current.starts_with("// Auto-generated by ts-rs") {
        // Already stamped — keep run idempotent so CI diff only shows real
        // changes from Rust source.
        return Ok(());
    }
    let mut f = fs::File::create(path)?;
    f.write_all(WARNING_HEADER.as_bytes())?;
    f.write_all(current.as_bytes())?;
    Ok(())
}

/// Walk `dir` recursively and prepend the warning header to every `.ts`
/// file found. Counts stamped files (fresh + already-stamped skipped).
fn stamp_recursively(dir: &Path, stamped: &mut usize) -> std::io::Result<()> {
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_dir() {
            stamp_recursively(&path, stamped)?;
        } else if path.extension().and_then(|s| s.to_str()) == Some("ts") {
            prepend_header(&path)?;
            *stamped += 1;
        }
    }
    Ok(())
}

/// Export `T` and every type it transitively references.
///
/// Uses `export_all_to(dir)` with the absolute workspace-root-relative
/// output dir. The `#[ts(export)]` attributes on each type intentionally
/// DO NOT carry an `export_to = "..."` so the `dir` we pass here is
/// the single source of truth for the output path. This avoids ts-rs's
/// tendency to resolve relative `export_to` paths against the runtime
/// `CARGO_MANIFEST_DIR` of the test binary (parkhub-server) instead of
/// the derive's crate (parkhub-common), which otherwise writes bindings
/// into `parkhub-server/parkhub-web/...` — wrong tree.
fn export<T: TS + 'static>(dir: &Path) -> std::io::Result<()> {
    <T as TS>::export_all_to(dir).map_err(|e| std::io::Error::other(format!("ts-rs export: {e}")))
}

#[test]
fn export_all_types() {
    let dir = output_dir();
    fs::create_dir_all(&dir).expect("create output dir");
    println!("ts_export: writing to {}", dir.display());

    // ── Protocol wrappers ────────────────────────────────────────────────
    // `ApiResponse<T>` and `PaginatedResponse<T>` are generic; ts-rs emits
    // a generic interface so a single export covers every T instantiation.
    export::<ApiResponse<()>>(&dir).unwrap();
    export::<ApiError>(&dir).unwrap();
    export::<ResponseMeta>(&dir).unwrap();
    export::<PaginatedResponse<()>>(&dir).unwrap();
    export::<LoginRequest>(&dir).unwrap();
    export::<LoginResponse>(&dir).unwrap();
    export::<RefreshTokenRequest>(&dir).unwrap();
    export::<RegisterRequest>(&dir).unwrap();

    // ── User ─────────────────────────────────────────────────────────────
    export::<User>(&dir).unwrap();
    export::<UserRole>(&dir).unwrap();
    export::<UserPreferences>(&dir).unwrap();
    export::<AuthTokens>(&dir).unwrap();

    // ── Parking lot / slot ──────────────────────────────────────────────
    export::<ParkingLot>(&dir).unwrap();
    export::<ParkingFloor>(&dir).unwrap();
    export::<ParkingSlot>(&dir).unwrap();
    export::<SlotType>(&dir).unwrap();
    export::<SlotStatus>(&dir).unwrap();
    export::<SlotBookingInfo>(&dir).unwrap();
    export::<SlotFeature>(&dir).unwrap();
    export::<SlotPosition>(&dir).unwrap();
    export::<LotStatus>(&dir).unwrap();
    export::<PricingInfo>(&dir).unwrap();
    export::<PricingRate>(&dir).unwrap();
    export::<OperatingHours>(&dir).unwrap();
    export::<DayHours>(&dir).unwrap();
    export::<DynamicPricingRules>(&dir).unwrap();
    export::<DynamicPriceResult>(&dir).unwrap();

    // ── Bookings + vehicles ─────────────────────────────────────────────
    export::<Booking>(&dir).unwrap();
    export::<BookingStatus>(&dir).unwrap();
    export::<BookingPricing>(&dir).unwrap();
    export::<PaymentStatus>(&dir).unwrap();
    export::<Vehicle>(&dir).unwrap();
    export::<VehicleType>(&dir).unwrap();
    export::<FuelType>(&dir).unwrap();
    export::<CreditTransaction>(&dir).unwrap();
    export::<CreditTransactionType>(&dir).unwrap();

    // ── Feature models used by v5 screens ───────────────────────────────
    export::<GuestBooking>(&dir).unwrap();
    export::<SwapRequest>(&dir).unwrap();
    export::<SwapRequestStatus>(&dir).unwrap();
    export::<Announcement>(&dir).unwrap();
    export::<AnnouncementSeverity>(&dir).unwrap();
    export::<Notification>(&dir).unwrap();
    export::<NotificationType>(&dir).unwrap();
    export::<AbsenceType>(&dir).unwrap();
    export::<Absence>(&dir).unwrap();
    export::<AbsencePattern>(&dir).unwrap();
    export::<ProposalStatus>(&dir).unwrap();
    export::<TranslationProposal>(&dir).unwrap();
    export::<TranslationOverride>(&dir).unwrap();

    // ── EV charging ─────────────────────────────────────────────────────
    export::<ConnectorType>(&dir).unwrap();
    export::<EvChargerStatus>(&dir).unwrap();
    export::<EvCharger>(&dir).unwrap();
    export::<ChargingSessionStatus>(&dir).unwrap();
    export::<ChargingSession>(&dir).unwrap();

    // Note: server-side DTOs in parkhub-server/src/api/{calendar,team}.rs
    // (CalendarEvent, TeamMember, TeamMemberStatus) also derive `TS` and
    // emit via the hidden `export_bindings_<type>` test that ts-rs adds
    // when the enclosing module is compiled as a test crate. Running
    // `cargo test --features gen-types -p parkhub-server` — which this
    // test file is part of — compiles the parkhub-server test binary and
    // triggers those hidden tests alongside `export_all_types`. The CI
    // workflow invokes exactly this command, so all three paths converge
    // on the same output directory.

    // ── Stamp warning header on every emitted .ts file ──────────────────
    // Walk recursively so files ts-rs emits into subdirectories (e.g.
    // `serde_json/JsonValue.ts` when `serde-json-impl` is enabled) also
    // pick up the header. Shallow readdir missed the subdir in earlier
    // iterations of this test.
    let mut stamped = 0usize;
    stamp_recursively(&dir, &mut stamped).expect("stamp headers recursively");
    assert!(
        stamped >= MIN_EXPECTED_FILES,
        "expected >= {MIN_EXPECTED_FILES} .ts files in {}, got {stamped}. \
         Either a feature regression turned off the ts-rs derives, or the \
         hidden export_bindings_* tests have not run yet.",
        dir.display(),
    );
    println!("ts_export: stamped warning header on {stamped} files");
}
