apiVersion: v1
kind: Secret
metadata:
  name: {{ include "parkhub.fullname" . }}
  labels:
    {{- include "parkhub.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.config.adminPassword }}
  PARKHUB_ADMIN_PASSWORD: {{ .Values.config.adminPassword | quote }}
  {{- end }}
  {{- if .Values.config.dbPassphrase }}
  PARKHUB_DB_PASSPHRASE: {{ .Values.config.dbPassphrase | quote }}
  {{- end }}
  {{- if .Values.config.smtp.host }}
  SMTP_HOST: {{ .Values.config.smtp.host | quote }}
  {{- end }}
  {{- if .Values.config.smtp.user }}
  SMTP_USER: {{ .Values.config.smtp.user | quote }}
  {{- end }}
  {{- if .Values.config.smtp.password }}
  SMTP_PASS: {{ .Values.config.smtp.password | quote }}
  {{- end }}
  {{- if .Values.config.stripe.secretKey }}
  STRIPE_SECRET_KEY: {{ .Values.config.stripe.secretKey | quote }}
  {{- end }}
  {{- if .Values.config.stripe.webhookSecret }}
  STRIPE_WEBHOOK_SECRET: {{ .Values.config.stripe.webhookSecret | quote }}
  {{- end }}
  {{- if .Values.config.oauth.google.clientId }}
  OAUTH_GOOGLE_CLIENT_ID: {{ .Values.config.oauth.google.clientId | quote }}
  {{- end }}
  {{- if .Values.config.oauth.google.clientSecret }}
  OAUTH_GOOGLE_CLIENT_SECRET: {{ .Values.config.oauth.google.clientSecret | quote }}
  {{- end }}
  {{- if .Values.config.oauth.github.clientId }}
  OAUTH_GITHUB_CLIENT_ID: {{ .Values.config.oauth.github.clientId | quote }}
  {{- end }}
  {{- if .Values.config.oauth.github.clientSecret }}
  OAUTH_GITHUB_CLIENT_SECRET: {{ .Values.config.oauth.github.clientSecret | quote }}
  {{- end }}
